[project]
name = "reel-77"
version = "0.1.0"
description = "Reel 77 (柒柒画片机) - A stylish slideshow application with background music"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pillow>=11.3.0",
    "pygame>=2.6.1",
    "pyqt6>=6.9.1",
]
